Services/Services.Identity/Services.Identity.Web/ViewModels/Login/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Services.Identity.Web.ViewModels.Login
{
    public class LoginViewModel
    {
        [Required] public string Username { get; set; }

        [Required] public string Password { get; set; }

        [Required] public string ReturnUrl { get; set; }
    }
}

Services/Services.Identity/Services.Identity.Web/ViewModels/Logout/LogoutViewModel.cs
namespace Services.Identity.Web.ViewModels.Logout
{
    public class LogoutViewModel
    {
        public string ReturnUrl { get; set; }
    }
}

Services/Services.Identity/Services.Identity.Web/Controllers/AuthenticationController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Common.Requests.Common;
using Services.Identity.Application.Interfaces.Identity;
using Services.Identity.Web.ViewModels.Login;
using Services.Identity.Web.ViewModels.Logout;

namespace Services.Identity.Web.Controllers
{
    [AllowAnonymous]
    public class AuthenticationController : BaseController
    {
        private readonly IAuthenticationService _authenticationService;

        public AuthenticationController(
            IAuthenticationService authenticationService
        )
        {
            _authenticationService = authenticationService;
        }

        [HttpGet]
        public IActionResult Login(string returnUrl)
        {
            return View(new LoginViewModel() {ReturnUrl = returnUrl});
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var result = await _authenticationService.SignInAsync(model.Username, model.Password, model.ReturnUrl);
            if (result.Succeeded)
            {
                return Redirect(model.ReturnUrl);
            }

            AddModelErrors(result.Errors);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Logout(LogoutViewModel model)
        {
            var result = await _authenticationService.SignOut(model.ReturnUrl);
            if (result.Succeeded)
            {
                return Redirect(model.ReturnUrl);
            }

            return BadRequest(new ErrorResponse(400, result.Errors));
        }
    }
}

Services/Services.Identity/Services.Identity.Web/Controllers/BaseController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;

namespace Services.Identity.Web.Controllers
{
    public abstract class BaseController : Controller
    {
        protected void AddModelErrors(IEnumerable<string> errors)
        {
            foreach (var error in errors)
            {
                ModelState.AddModelError(string.Empty, error);
            }
        }

        protected void AddModelError(string error)
        {
            ModelState.AddModelError(string.Empty, error);
        }
    }
}

Services/Services.Identity/Services.Identity.Web/Controllers/RegistrationController.cs
using System.Threading.Tasks;
using IdentityServer4.Services;
using Microsoft.AspNetCore.Mvc;
using Services.Identity.Application.Interfaces.Identity;
using Services.Identity.Domain.Entities;
using Services.Identity.Web.ViewModels.Login;
using Services.Identity.Web.ViewModels.Registration;

namespace Services.Identity.Web.Controllers
{
    public class RegistrationController : BaseController
    {
        private readonly IIdentityServerInteractionService _identityServerInteractionService;
        private readonly IIdentityService _identityService;

        public RegistrationController(IIdentityService identityService,
            IIdentityServerInteractionService identityServerInteractionService)
        {
            _identityService = identityService;
            _identityServerInteractionService = identityServerInteractionService;
        }

        [HttpGet]
        public IActionResult Register(string returnUrl)
        {
            return View(new RegisterViewModel() {ReturnUrl = returnUrl});
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (!_identityServerInteractionService.IsValidReturnUrl(model.ReturnUrl))
            {
                AddModelError("Invalid return url");
                return View(model);
            }

            var applicationUser = new ApplicationUser(model.FirstName, model.LastName, model.Email, model.Email);
            var result = await _identityService.CreateAsync(applicationUser, model.Password);

            if (result.Succeeded)
                return RedirectToAction("Login", "Authentication", new LoginViewModel() {ReturnUrl = model.ReturnUrl});

            AddModelErrors(result.Errors);
            return View(model);
        }
    }
}

Services/Services.Identity/Services.Identity.Web/Views/Authentication/Login.cshtml
@model Services.Identity.Web.ViewModels.Login.LoginViewModel

@{
    ViewBag.Title = "Login";
    Layout = "_Layout";
}

@*Flex container*@
<div class="container-fluid p-4">
    @*Form container*@
    <div class="w-full max-w-xs">
        <h1 class="text-center text-xl pb-2 font-bold"> Welcome,</h1>

        @*Form data*@
        <form class="p-2" asp-controller="Authentication" asp-action="Login" method="post">
            <input type="hidden" asp-for="@Model.ReturnUrl"/>

            @*Username*@
            <div class="mb-2">
                <label for="username" class="custom-label">
                    Username
                </label>
                <input asp-for="@Model.Username" id="username" class="shadow-input-box" type="text" placeholder="Username">
                <span asp-validation-for="Username" class="span-validation"></span>
            </div>

            @*Password*@
            <div class="mb-2">
                <label for="password" class="custom-label">
                    Password
                </label>
                <input asp-for="@Model.Password" id="password" class="shadow-input-box" type="password" placeholder="******************">
                <span asp-validation-for="Password" class="span-validation"></span>
            </div>

            @*Sign In / Register / Forgot*@
            <div class="flex items-center justify-between">
                <div>
                    <button type="submit" id="sigin-button"
                            class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                        Sign In
                    </button>
                </div>

                <div>
                    <a asp-controller="Registration" asp-action="Register" asp-route-returnUrl="@Model.ReturnUrl" id="register-button"
                       class="bg-indigo-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                        Register
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>

Services/Services.Identity/Services.Identity.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="">
<head>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/site.css">
</head>
<body>

@RenderBody()

</body>
</html>

Services/Services.Identity/Services.Identity.Web/Views/Shared/_ValidationSummary.cshtml
@if (ViewContext.ModelState.IsValid == false)
{
    <div class="alert alert-danger">
        <strong>Error</strong>
        <div asp-validation-summary="All" class="danger"></div>
    </div>
}